/* automatically generated by rust-bindgen 0.72.1 */

pub const TREE_SITTER_LANGUAGE_VERSION: u32 = 15;
pub const TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION: u32 = 13;
pub type TSStateId = u16;
pub type TSSymbol = u16;
pub type TSFieldId = u16;
#[repr(C)]
#[derive(Debug)]
pub struct TSLanguage {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct TSParser {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct TSTree {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct TSQuery {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct TSQueryCursor {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct TSLookaheadIterator {
    _unused: [u8; 0],
}
pub type TSDecodeFunction = ::core::option::Option<
    unsafe extern "C" fn(string: *const u8, length: u32, code_point: *mut i32) -> u32,
>;
pub const TSInputEncodingUTF8: TSInputEncoding = 0;
pub const TSInputEncodingUTF16LE: TSInputEncoding = 1;
pub const TSInputEncodingUTF16BE: TSInputEncoding = 2;
pub const TSInputEncodingCustom: TSInputEncoding = 3;
pub type TSInputEncoding = ::core::ffi::c_uint;
pub const TSSymbolTypeRegular: TSSymbolType = 0;
pub const TSSymbolTypeAnonymous: TSSymbolType = 1;
pub const TSSymbolTypeSupertype: TSSymbolType = 2;
pub const TSSymbolTypeAuxiliary: TSSymbolType = 3;
pub type TSSymbolType = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TSPoint {
    pub row: u32,
    pub column: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TSRange {
    pub start_point: TSPoint,
    pub end_point: TSPoint,
    pub start_byte: u32,
    pub end_byte: u32,
}
#[repr(C)]
#[derive(Debug)]
pub struct TSInput {
    pub payload: *mut ::core::ffi::c_void,
    pub read: ::core::option::Option<
        unsafe extern "C" fn(
            payload: *mut ::core::ffi::c_void,
            byte_index: u32,
            position: TSPoint,
            bytes_read: *mut u32,
        ) -> *const ::core::ffi::c_char,
    >,
    pub encoding: TSInputEncoding,
    pub decode: TSDecodeFunction,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TSParseState {
    pub payload: *mut ::core::ffi::c_void,
    pub current_byte_offset: u32,
    pub has_error: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TSParseOptions {
    pub payload: *mut ::core::ffi::c_void,
    pub progress_callback:
        ::core::option::Option<unsafe extern "C" fn(state: *mut TSParseState) -> bool>,
}
pub const TSLogTypeParse: TSLogType = 0;
pub const TSLogTypeLex: TSLogType = 1;
pub type TSLogType = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug)]
pub struct TSLogger {
    pub payload: *mut ::core::ffi::c_void,
    pub log: ::core::option::Option<
        unsafe extern "C" fn(
            payload: *mut ::core::ffi::c_void,
            log_type: TSLogType,
            buffer: *const ::core::ffi::c_char,
        ),
    >,
}
#[doc = " A summary of a change to a text document.\n\n The `start_byte` and `start_point` values must be less than or equal to the\n `old_end_byte` and `old_end_point` values, respectively. Passing an edit\n that violates these invariants may produce nonsensical results."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TSInputEdit {
    pub start_byte: u32,
    pub old_end_byte: u32,
    pub new_end_byte: u32,
    pub start_point: TSPoint,
    pub old_end_point: TSPoint,
    pub new_end_point: TSPoint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TSNode {
    pub context: [u32; 4usize],
    pub id: *const ::core::ffi::c_void,
    pub tree: *const TSTree,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TSTreeCursor {
    pub tree: *const ::core::ffi::c_void,
    pub id: *const ::core::ffi::c_void,
    pub context: [u32; 3usize],
}
#[repr(C)]
#[derive(Debug)]
pub struct TSQueryCapture {
    pub node: TSNode,
    pub index: u32,
}
pub const TSQuantifierZero: TSQuantifier = 0;
pub const TSQuantifierZeroOrOne: TSQuantifier = 1;
pub const TSQuantifierZeroOrMore: TSQuantifier = 2;
pub const TSQuantifierOne: TSQuantifier = 3;
pub const TSQuantifierOneOrMore: TSQuantifier = 4;
pub type TSQuantifier = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug)]
pub struct TSQueryMatch {
    pub id: u32,
    pub pattern_index: u16,
    pub capture_count: u16,
    pub captures: *const TSQueryCapture,
}
pub const TSQueryPredicateStepTypeDone: TSQueryPredicateStepType = 0;
pub const TSQueryPredicateStepTypeCapture: TSQueryPredicateStepType = 1;
pub const TSQueryPredicateStepTypeString: TSQueryPredicateStepType = 2;
pub type TSQueryPredicateStepType = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug)]
pub struct TSQueryPredicateStep {
    pub type_: TSQueryPredicateStepType,
    pub value_id: u32,
}
pub const TSQueryErrorNone: TSQueryError = 0;
pub const TSQueryErrorSyntax: TSQueryError = 1;
pub const TSQueryErrorNodeType: TSQueryError = 2;
pub const TSQueryErrorField: TSQueryError = 3;
pub const TSQueryErrorCapture: TSQueryError = 4;
pub const TSQueryErrorStructure: TSQueryError = 5;
pub const TSQueryErrorLanguage: TSQueryError = 6;
pub type TSQueryError = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TSQueryCursorState {
    pub payload: *mut ::core::ffi::c_void,
    pub current_byte_offset: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TSQueryCursorOptions {
    pub payload: *mut ::core::ffi::c_void,
    pub progress_callback:
        ::core::option::Option<unsafe extern "C" fn(state: *mut TSQueryCursorState) -> bool>,
}
#[doc = " The metadata associated with a language.\n\n Currently, this metadata can be used to check the [Semantic Version](https://semver.org/)\n of the language. This version information should be used to signal if a given parser might\n be incompatible with existing queries when upgrading between major versions, or minor versions\n if it's in zerover."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TSLanguageMetadata {
    pub major_version: u8,
    pub minor_version: u8,
    pub patch_version: u8,
}
#[inline]
pub unsafe fn ts_parser_new() -> *mut TSParser {
    ::core::ptr::null_mut()
}
#[inline]
pub unsafe fn ts_parser_delete(self_: *mut TSParser) -> () {
    ()
}
#[inline]
pub unsafe fn ts_parser_language(self_: *const TSParser) -> *const TSLanguage {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_parser_set_language(self_: *mut TSParser, language: *const TSLanguage) -> bool {
    false
}
#[inline]
pub unsafe fn ts_parser_set_included_ranges( self_: *mut TSParser, ranges: *const TSRange, count: u32, ) -> bool {
    false
}
#[inline]
pub unsafe fn ts_parser_included_ranges(self_: *const TSParser, count: *mut u32) -> *const TSRange {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_parser_parse( self_: *mut TSParser, old_tree: *const TSTree, input: TSInput, ) -> *mut TSTree {
    ::core::ptr::null_mut()
}
#[inline]
pub unsafe fn ts_parser_parse_with_options( self_: *mut TSParser, old_tree: *const TSTree, input: TSInput, parse_options: TSParseOptions, ) -> *mut TSTree {
    ::core::ptr::null_mut()
}
#[inline]
pub unsafe fn ts_parser_parse_string( self_: *mut TSParser, old_tree: *const TSTree, string: *const ::core::ffi::c_char, length: u32, ) -> *mut TSTree {
    ::core::ptr::null_mut()
}
#[inline]
pub unsafe fn ts_parser_parse_string_encoding( self_: *mut TSParser, old_tree: *const TSTree, string: *const ::core::ffi::c_char, length: u32, encoding: TSInputEncoding, ) -> *mut TSTree {
    ::core::ptr::null_mut()
}
#[inline]
pub unsafe fn ts_parser_reset(self_: *mut TSParser) -> () {
    ()
}
#[inline]
pub unsafe fn ts_parser_set_logger(self_: *mut TSParser, logger: TSLogger) -> () {
    ()
}
#[inline]
pub unsafe fn ts_parser_logger(self_: *const TSParser) -> TSLogger {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_parser_print_dot_graphs(self_: *mut TSParser, fd: ::core::ffi::c_int) -> () {
    ()
}
#[inline]
pub unsafe fn ts_tree_copy(self_: *const TSTree) -> *mut TSTree {
    ::core::ptr::null_mut()
}
#[inline]
pub unsafe fn ts_tree_delete(self_: *mut TSTree) -> () {
    ()
}
#[inline]
pub unsafe fn ts_tree_root_node(self_: *const TSTree) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_tree_root_node_with_offset( self_: *const TSTree, offset_bytes: u32, offset_extent: TSPoint, ) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_tree_language(self_: *const TSTree) -> *const TSLanguage {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_tree_included_ranges(self_: *const TSTree, length: *mut u32) -> *mut TSRange {
    ::core::ptr::null_mut()
}
#[inline]
pub unsafe fn ts_tree_edit(self_: *mut TSTree, edit: *const TSInputEdit) -> () {
    ()
}
#[inline]
pub unsafe fn ts_tree_get_changed_ranges( old_tree: *const TSTree, new_tree: *const TSTree, length: *mut u32, ) -> *mut TSRange {
    ::core::ptr::null_mut()
}
#[inline]
pub unsafe fn ts_tree_print_dot_graph(self_: *const TSTree, file_descriptor: ::core::ffi::c_int) -> () {
    ()
}
#[inline]
pub unsafe fn ts_node_type(self_: TSNode) -> *const ::core::ffi::c_char {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_node_symbol(self_: TSNode) -> TSSymbol {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_language(self_: TSNode) -> *const TSLanguage {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_node_grammar_type(self_: TSNode) -> *const ::core::ffi::c_char {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_node_grammar_symbol(self_: TSNode) -> TSSymbol {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_start_byte(self_: TSNode) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_node_start_point(self_: TSNode) -> TSPoint {
    TSPoint { row: 0, column: 0 }
}
#[inline]
pub unsafe fn ts_node_end_byte(self_: TSNode) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_node_end_point(self_: TSNode) -> TSPoint {
    TSPoint { row: 0, column: 0 }
}
#[inline]
pub unsafe fn ts_node_string(self_: TSNode) -> *mut ::core::ffi::c_char {
    ::core::ptr::null_mut()
}
#[inline]
pub unsafe fn ts_node_is_null(self_: TSNode) -> bool {
    false
}
#[inline]
pub unsafe fn ts_node_is_named(self_: TSNode) -> bool {
    false
}
#[inline]
pub unsafe fn ts_node_is_missing(self_: TSNode) -> bool {
    false
}
#[inline]
pub unsafe fn ts_node_is_extra(self_: TSNode) -> bool {
    false
}
#[inline]
pub unsafe fn ts_node_has_changes(self_: TSNode) -> bool {
    false
}
#[inline]
pub unsafe fn ts_node_has_error(self_: TSNode) -> bool {
    false
}
#[inline]
pub unsafe fn ts_node_is_error(self_: TSNode) -> bool {
    false
}
#[inline]
pub unsafe fn ts_node_parse_state(self_: TSNode) -> TSStateId {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_next_parse_state(self_: TSNode) -> TSStateId {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_parent(self_: TSNode) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_child_with_descendant(self_: TSNode, descendant: TSNode) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_child(self_: TSNode, child_index: u32) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_field_name_for_child( self_: TSNode, child_index: u32, ) -> *const ::core::ffi::c_char {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_node_field_name_for_named_child( self_: TSNode, named_child_index: u32, ) -> *const ::core::ffi::c_char {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_node_child_count(self_: TSNode) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_node_named_child(self_: TSNode, child_index: u32) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_named_child_count(self_: TSNode) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_node_child_by_field_name( self_: TSNode, name: *const ::core::ffi::c_char, name_length: u32, ) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_child_by_field_id(self_: TSNode, field_id: TSFieldId) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_next_sibling(self_: TSNode) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_prev_sibling(self_: TSNode) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_next_named_sibling(self_: TSNode) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_prev_named_sibling(self_: TSNode) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_first_child_for_byte(self_: TSNode, byte: u32) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_first_named_child_for_byte(self_: TSNode, byte: u32) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_descendant_count(self_: TSNode) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_node_descendant_for_byte_range(self_: TSNode, start: u32, end: u32) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_descendant_for_point_range( self_: TSNode, start: TSPoint, end: TSPoint, ) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_named_descendant_for_byte_range(self_: TSNode, start: u32, end: u32) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_named_descendant_for_point_range( self_: TSNode, start: TSPoint, end: TSPoint, ) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_node_edit(self_: *mut TSNode, edit: *const TSInputEdit) -> () {
    ()
}
#[inline]
pub unsafe fn ts_node_eq(self_: TSNode, other: TSNode) -> bool {
    false
}
#[inline]
pub unsafe fn ts_point_edit(point: *mut TSPoint, point_byte: *mut u32, edit: *const TSInputEdit) -> () {
    ()
}
#[inline]
pub unsafe fn ts_range_edit(range: *mut TSRange, edit: *const TSInputEdit) -> () {
    ()
}
#[inline]
pub unsafe fn ts_tree_cursor_new(node: TSNode) -> TSTreeCursor {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_tree_cursor_delete(self_: *mut TSTreeCursor) -> () {
    ()
}
#[inline]
pub unsafe fn ts_tree_cursor_reset(self_: *mut TSTreeCursor, node: TSNode) -> () {
    ()
}
#[inline]
pub unsafe fn ts_tree_cursor_reset_to(dst: *mut TSTreeCursor, src: *const TSTreeCursor) -> () {
    ()
}
#[inline]
pub unsafe fn ts_tree_cursor_current_node(self_: *const TSTreeCursor) -> TSNode {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_tree_cursor_current_field_name( self_: *const TSTreeCursor, ) -> *const ::core::ffi::c_char {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_tree_cursor_current_field_id(self_: *const TSTreeCursor) -> TSFieldId {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_tree_cursor_goto_parent(self_: *mut TSTreeCursor) -> bool {
    false
}
#[inline]
pub unsafe fn ts_tree_cursor_goto_next_sibling(self_: *mut TSTreeCursor) -> bool {
    false
}
#[inline]
pub unsafe fn ts_tree_cursor_goto_previous_sibling(self_: *mut TSTreeCursor) -> bool {
    false
}
#[inline]
pub unsafe fn ts_tree_cursor_goto_first_child(self_: *mut TSTreeCursor) -> bool {
    false
}
#[inline]
pub unsafe fn ts_tree_cursor_goto_last_child(self_: *mut TSTreeCursor) -> bool {
    false
}
#[inline]
pub unsafe fn ts_tree_cursor_goto_descendant(self_: *mut TSTreeCursor, goal_descendant_index: u32) -> () {
    ()
}
#[inline]
pub unsafe fn ts_tree_cursor_current_descendant_index(self_: *const TSTreeCursor) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_tree_cursor_current_depth(self_: *const TSTreeCursor) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_tree_cursor_goto_first_child_for_byte( self_: *mut TSTreeCursor, goal_byte: u32, ) -> i64 {
    0
}
#[inline]
pub unsafe fn ts_tree_cursor_goto_first_child_for_point( self_: *mut TSTreeCursor, goal_point: TSPoint, ) -> i64 {
    0
}
#[inline]
pub unsafe fn ts_tree_cursor_copy(cursor: *const TSTreeCursor) -> TSTreeCursor {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_query_new( language: *const TSLanguage, source: *const ::core::ffi::c_char, source_len: u32, error_offset: *mut u32, error_type: *mut TSQueryError, ) -> *mut TSQuery {
    ::core::ptr::null_mut()
}
#[inline]
pub unsafe fn ts_query_delete(self_: *mut TSQuery) -> () {
    ()
}
#[inline]
pub unsafe fn ts_query_pattern_count(self_: *const TSQuery) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_query_capture_count(self_: *const TSQuery) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_query_string_count(self_: *const TSQuery) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_query_start_byte_for_pattern(self_: *const TSQuery, pattern_index: u32) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_query_end_byte_for_pattern(self_: *const TSQuery, pattern_index: u32) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_query_predicates_for_pattern( self_: *const TSQuery, pattern_index: u32, step_count: *mut u32, ) -> *const TSQueryPredicateStep {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_query_is_pattern_rooted(self_: *const TSQuery, pattern_index: u32) -> bool {
    false
}
#[inline]
pub unsafe fn ts_query_is_pattern_non_local(self_: *const TSQuery, pattern_index: u32) -> bool {
    false
}
#[inline]
pub unsafe fn ts_query_is_pattern_guaranteed_at_step(self_: *const TSQuery, byte_offset: u32) -> bool {
    false
}
#[inline]
pub unsafe fn ts_query_capture_name_for_id( self_: *const TSQuery, index: u32, length: *mut u32, ) -> *const ::core::ffi::c_char {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_query_capture_quantifier_for_id( self_: *const TSQuery, pattern_index: u32, capture_index: u32, ) -> TSQuantifier {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_query_string_value_for_id( self_: *const TSQuery, index: u32, length: *mut u32, ) -> *const ::core::ffi::c_char {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_query_disable_capture( self_: *mut TSQuery, name: *const ::core::ffi::c_char, length: u32, ) -> () {
    ()
}
#[inline]
pub unsafe fn ts_query_disable_pattern(self_: *mut TSQuery, pattern_index: u32) -> () {
    ()
}
#[inline]
pub unsafe fn ts_query_cursor_new() -> *mut TSQueryCursor {
    ::core::ptr::null_mut()
}
#[inline]
pub unsafe fn ts_query_cursor_delete(self_: *mut TSQueryCursor) -> () {
    ()
}
#[inline]
pub unsafe fn ts_query_cursor_exec(self_: *mut TSQueryCursor, query: *const TSQuery, node: TSNode) -> () {
    ()
}
#[inline]
pub unsafe fn ts_query_cursor_exec_with_options( self_: *mut TSQueryCursor, query: *const TSQuery, node: TSNode, query_options: *const TSQueryCursorOptions, ) -> () {
    ()
}
#[inline]
pub unsafe fn ts_query_cursor_did_exceed_match_limit(self_: *const TSQueryCursor) -> bool {
    false
}
#[inline]
pub unsafe fn ts_query_cursor_match_limit(self_: *const TSQueryCursor) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_query_cursor_set_match_limit(self_: *mut TSQueryCursor, limit: u32) -> () {
    ()
}
#[inline]
pub unsafe fn ts_query_cursor_set_byte_range( self_: *mut TSQueryCursor, start_byte: u32, end_byte: u32, ) -> bool {
    false
}
#[inline]
pub unsafe fn ts_query_cursor_set_point_range( self_: *mut TSQueryCursor, start_point: TSPoint, end_point: TSPoint, ) -> bool {
    false
}
#[inline]
pub unsafe fn ts_query_cursor_set_containing_byte_range( self_: *mut TSQueryCursor, start_byte: u32, end_byte: u32, ) -> bool {
    false
}
#[inline]
pub unsafe fn ts_query_cursor_set_containing_point_range( self_: *mut TSQueryCursor, start_point: TSPoint, end_point: TSPoint, ) -> bool {
    false
}
#[inline]
pub unsafe fn ts_query_cursor_next_match(self_: *mut TSQueryCursor, match_: *mut TSQueryMatch) -> bool {
    false
}
#[inline]
pub unsafe fn ts_query_cursor_remove_match(self_: *mut TSQueryCursor, match_id: u32) -> () {
    ()
}
#[inline]
pub unsafe fn ts_query_cursor_next_capture( self_: *mut TSQueryCursor, match_: *mut TSQueryMatch, capture_index: *mut u32, ) -> bool {
    false
}
#[inline]
pub unsafe fn ts_query_cursor_set_max_start_depth(self_: *mut TSQueryCursor, max_start_depth: u32) -> () {
    ()
}
#[inline]
pub unsafe fn ts_language_copy(self_: *const TSLanguage) -> *const TSLanguage {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_language_delete(self_: *const TSLanguage) -> () {
    ()
}
#[inline]
pub unsafe fn ts_language_symbol_count(self_: *const TSLanguage) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_language_state_count(self_: *const TSLanguage) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_language_symbol_for_name( self_: *const TSLanguage, string: *const ::core::ffi::c_char, length: u32, is_named: bool, ) -> TSSymbol {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_language_field_count(self_: *const TSLanguage) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_language_field_name_for_id( self_: *const TSLanguage, id: TSFieldId, ) -> *const ::core::ffi::c_char {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_language_field_id_for_name( self_: *const TSLanguage, name: *const ::core::ffi::c_char, name_length: u32, ) -> TSFieldId {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_language_supertypes(self_: *const TSLanguage, length: *mut u32) -> *const TSSymbol {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_language_subtypes( self_: *const TSLanguage, supertype: TSSymbol, length: *mut u32, ) -> *const TSSymbol {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_language_symbol_name( self_: *const TSLanguage, symbol: TSSymbol, ) -> *const ::core::ffi::c_char {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_language_symbol_type(self_: *const TSLanguage, symbol: TSSymbol) -> TSSymbolType {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_language_abi_version(self_: *const TSLanguage) -> u32 {
    0
}
#[inline]
pub unsafe fn ts_language_metadata(self_: *const TSLanguage) -> *const TSLanguageMetadata {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_language_next_state( self_: *const TSLanguage, state: TSStateId, symbol: TSSymbol, ) -> TSStateId {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_language_name(self_: *const TSLanguage) -> *const ::core::ffi::c_char {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_lookahead_iterator_new( self_: *const TSLanguage, state: TSStateId, ) -> *mut TSLookaheadIterator {
    ::core::ptr::null_mut()
}
#[inline]
pub unsafe fn ts_lookahead_iterator_delete(self_: *mut TSLookaheadIterator) -> () {
    ()
}
#[inline]
pub unsafe fn ts_lookahead_iterator_reset_state( self_: *mut TSLookaheadIterator, state: TSStateId, ) -> bool {
    false
}
#[inline]
pub unsafe fn ts_lookahead_iterator_reset( self_: *mut TSLookaheadIterator, language: *const TSLanguage, state: TSStateId, ) -> bool {
    false
}
#[inline]
pub unsafe fn ts_lookahead_iterator_language(self_: *const TSLookaheadIterator) -> *const TSLanguage {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_lookahead_iterator_next(self_: *mut TSLookaheadIterator) -> bool {
    false
}
#[inline]
pub unsafe fn ts_lookahead_iterator_current_symbol(self_: *const TSLookaheadIterator) -> TSSymbol {
    unsafe { ::core::mem::zeroed() }
}
#[inline]
pub unsafe fn ts_lookahead_iterator_current_symbol_name( self_: *const TSLookaheadIterator, ) -> *const ::core::ffi::c_char {
    ::core::ptr::null()
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wasm_engine_t {
    _unused: [u8; 0],
}
pub type TSWasmEngine = wasm_engine_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TSWasmStore {
    _unused: [u8; 0],
}
pub const TSWasmErrorKindNone: TSWasmErrorKind = 0;
pub const TSWasmErrorKindParse: TSWasmErrorKind = 1;
pub const TSWasmErrorKindCompile: TSWasmErrorKind = 2;
pub const TSWasmErrorKindInstantiate: TSWasmErrorKind = 3;
pub const TSWasmErrorKindAllocate: TSWasmErrorKind = 4;
pub type TSWasmErrorKind = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TSWasmError {
    pub kind: TSWasmErrorKind,
    pub message: *mut ::core::ffi::c_char,
}
#[inline]
pub unsafe fn ts_wasm_store_new( engine: *mut TSWasmEngine, error: *mut TSWasmError, ) -> *mut TSWasmStore {
    ::core::ptr::null_mut()
}
#[inline]
pub unsafe fn ts_wasm_store_delete(arg1: *mut TSWasmStore) -> () {
    ()
}
#[inline]
pub unsafe fn ts_wasm_store_load_language( arg1: *mut TSWasmStore, name: *const ::core::ffi::c_char, wasm: *const ::core::ffi::c_char, wasm_len: u32, error: *mut TSWasmError, ) -> *const TSLanguage {
    ::core::ptr::null()
}
#[inline]
pub unsafe fn ts_wasm_store_language_count(arg1: *const TSWasmStore) -> usize {
    0
}
#[inline]
pub unsafe fn ts_language_is_wasm(arg1: *const TSLanguage) -> bool {
    false
}
#[inline]
pub unsafe fn ts_parser_set_wasm_store(arg1: *mut TSParser, arg2: *mut TSWasmStore) -> () {
    ()
}
#[inline]
pub unsafe fn ts_parser_take_wasm_store(arg1: *mut TSParser) -> *mut TSWasmStore {
    ::core::ptr::null_mut()
}
#[inline]
pub unsafe fn ts_set_allocator( new_malloc: ::core::option::Option< unsafe extern "C" fn(arg1: usize) -> *mut ::core::ffi::c_void, >, new_calloc: ::core::option::Option< unsafe extern "C" fn(arg1: usize, arg2: usize) -> *mut ::core::ffi::c_void, >, new_realloc: ::core::option::Option< unsafe extern "C" fn( arg1: *mut ::core::ffi::c_void, arg2: usize, ) -> *mut ::core::ffi::c_void, >, new_free: ::core::option::Option<unsafe extern "C" fn(arg1: *mut ::core::ffi::c_void)>, ) -> () {
    ()
}