[package]
name = "smol"
version = "2.0.2"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "WASM-compatible wrapper around smol"
publish = false

[dependencies]
async-channel.workspace = true
async-executor = "1.13.3"
async-lock.workspace = true
futures-lite.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
async-fs.workspace = true
async-io.workspace = true
async-net = "2.0.0"
async-process.workspace = true
blocking = "1.6.2"

[target.'cfg(target_family = "wasm")'.dependencies]
anyhow.workspace = true
base64.workspace = true
futures = "0.3"
serde.workspace = true
serde_json.workspace = true
uuid = { workspace = true, features = ["js"] }
wasm-bindgen-futures.workspace = true
wasm_rpc = { workspace = true }
